/**
 * JAYT VERIFIED SAVINGS DATA MODULE (SOT / UI RUNTIME BINDING)
 * AUTO-GENERATED (JAYT-244 M1-M3 PILOT)
 * Version: 3.401.0
 */

(function(root) {
  'use strict';

  var TIERED_SAVINGS_FEED = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "feed_version": "3.401.0",
  "feed_code": "JAYT_CANONICAL_SUPPLY_FEED_242",
  "generated_at": "2026-08-28T13:57:48.254Z",
  "governance_mandate": "CHỈ THỊ HỘI ĐỒNG — JAYT-244: M1-M3 PARALLEL PILOT EXECUTION",
  "city": "Đà Nẵng",
  "truth_matrix": {
    "tier_1_verified_deals": 6,
    "tier_2_official_programs": 10,
    "tier_3_verified_venues": 16,
    "tier_4_candidate_radars": 11,
    "total_monitored_cards": 43,
    "affiliate_commercial_cards": 0,
    "affiliate_policy": "STRICT_RADAR_CONTAINMENT_ZERO_COMMERCIAL_LINKS",
    "headline_summary": "Bảng Sự Thật Nguồn Cung: 6 Deal xác minh · 10 Chương trình nguồn · 16 Địa điểm xác minh · 11 Radar nguồn theo dõi"
  },
  "supply_board_matrix": [
    {
      "card_id": "CARD_217_01_METIZ_MEMBER",
      "claim_id": "CLM_208_01_METIZ_MEMBER",
      "bundle_id": "BUNDLE_DEAL_001_METIZ_U22",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "Metiz Cinema Đà Nẵng",
      "title": "Metiz Cinema — U22 Đồng Giá 55K/Vé 2D",
      "category": "CINEMA",
      "locality": "Hải Châu · Helio Center Đường 2/9",
      "customer_job": "Xem phim tiết kiệm",
      "source_url": "https://metiz.vn/promotion/khuyen-mai-gia-ve-u22-21.html",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_208_01_METIZ_U22_BUNDLE",
      "artifact_hash": "72422357f1e27c1ba16d6cb3a4d1a860dbaecb46c7ef52ef218e5321e78461f1",
      "visual_provenance": "assets/real-verified-assets/metiz-u22-student-official-poster.png",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "Thứ Ba đến Thứ Năm hàng tuần · Thành viên U22 tại Helio Center",
      "raw_quote_exact": "Áp dụng giá vé 2D chỉ 55.000đ cho thành viên Metiz Cinema từ 22 tuổi trở xuống, đối với mọi suất chiếu tại Metiz Cinema.",
      "terms": "Áp dụng cho thành viên dưới 22 tuổi xuất trình CCCD/thẻ SV. Mua vé trực tiếp tại quầy. Không áp dụng ngày lễ/suất đặc biệt.",
      "validity": "Thứ Ba đến Thứ Năm hàng tuần",
      "scope": "Metiz Cinema Helio Center Đà Nẵng",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_02_METIZ_SUPER_MONDAY",
      "claim_id": "CLM_208_02_METIZ_SUPER_MONDAY",
      "bundle_id": "BUNDLE_DEAL_002_METIZ_SUPER_MONDAY",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "Metiz Cinema Đà Nẵng",
      "title": "Metiz Cinema — Thứ Hai Siêu Hạng 55K",
      "category": "CINEMA",
      "locality": "Hải Châu · Helio Center Đường 2/9",
      "customer_job": "Xem phim đầu tuần",
      "source_url": "https://metiz.vn/promotion/thu-hai-sieu-hang.html",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_208_02_METIZ_MONDAY_BUNDLE",
      "artifact_hash": "72422357f1e27c1ba16d6cb3a4d1a860dbaecb46c7ef52ef218e5321e78461f1",
      "visual_provenance": "assets/real-verified-assets/metiz-u22-student-official-poster.png",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "Thứ Hai hàng tuần cho thành viên Metiz",
      "raw_quote_exact": "Đồng giá 55.000đ mọi suất chiếu Thứ 2 siêu hạng cho tất cả khách hàng thành viên.",
      "terms": "Áp dụng Thứ Hai hàng tuần cho thành viên.",
      "validity": "Thứ Hai hàng tuần",
      "scope": "Metiz Cinema Helio Center Đà Nẵng",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_03_STARLIGHT_PROMO",
      "claim_id": "CLM_208_03_STARLIGHT_PROMO",
      "bundle_id": "BUNDLE_DEAL_003_STARLIGHT_U22",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "Starlight Cinema Đà Nẵng",
      "title": "Starlight Cinema — U22 Đồng Giá 45K-50K/Vé",
      "category": "CINEMA",
      "locality": "Thanh Khê · TTTM Nguyễn Kim",
      "customer_job": "Xem phim rạp Starlight giá rẻ",
      "source_url": "https://starlight.vn/khuyen-mai.html",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_003_STARLIGHT_BUNDLE",
      "artifact_hash": "3daeb70ae5f3089d38c719e782625902bc6ba98bdfb21efb702ec4c979d678fa",
      "visual_provenance": "assets/real-verified-assets/starlight-u22-student-official-poster.jpg",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "Thứ Ba và Thứ Năm hàng tuần cho U22",
      "raw_quote_exact": "Đồng giá 45.000đ - 50.000đ cho thành viên U22 tại cụm rạp Starlight Nguyễn Kim Đà Nẵng.",
      "terms": "Xuất trình thẻ thành viên hoặc CCCD U22 tại quầy vé.",
      "validity": "Thứ Ba và Thứ Năm",
      "scope": "Starlight Cinema Nguyễn Kim Đà Nẵng",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_06_POPEYES",
      "claim_id": "CLM_208_06_POPEYES_COMBO",
      "bundle_id": "BUNDLE_SOURCE_004_POPEYES",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "Popeyes Louisiana Kitchen",
      "title": "Popeyes — Combo Gà Rán Giòn Cay Giảm 50%",
      "category": "FOOD",
      "locality": "Hải Châu & Ngũ Hành Sơn",
      "customer_job": "Ăn trưa no & tiết kiệm",
      "source_url": "https://popeyes.vn/promotions",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_004_POPEYES_BUNDLE",
      "artifact_hash": "28e183794a3175c5e8c454e99f0607c390dae6abffda7a514d24177d4b4df9d1",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "Giảm 50% cho miếng gà thứ 2 hoặc khi mua kèm combo",
      "raw_quote_exact": "Ưu đãi giảm giá 50% combo gà rán giòn cay áp dụng tại các chi nhánh Popeyes Đà Nẵng.",
      "terms": "Áp dụng tại quầy cho khách hàng dùng bữa tại chỗ hoặc mang đi.",
      "validity": "Theo thời hạn chương trình",
      "scope": "Các chi nhánh Popeyes Đà Nẵng",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_05_DOMINOS_PIZZA",
      "claim_id": "CLM_208_05_DOMINOS_BOGO",
      "bundle_id": "BUNDLE_SOURCE_003_DOMINOS",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "Domino's Pizza Đà Nẵng",
      "title": "Domino's Pizza — Mua 1 Tặng 1 Thứ Ba & Chủ Nhật",
      "category": "FOOD",
      "locality": "Hải Châu · Nguyễn Văn Linh",
      "customer_job": "Ăn pizza nhóm bạn bè",
      "source_url": "https://dominos.vn/promotions",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_003_DOMINOS_BUNDLE",
      "artifact_hash": "d35ca2d6657962baec4dbafaeeb586ef2e9faae2e01dfba986eebc89d2df8018",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "Mua 1 Pizza tặng 1 Pizza size M hoặc L",
      "raw_quote_exact": "Chương trình ưu đãi Mua 1 Tặng 1 Pizza áp dụng vào Thứ Ba và Chủ Nhật hàng tuần.",
      "terms": "Áp dụng khi mua Pizza size M hoặc L cùng loại hoặc giá trị tương đương.",
      "validity": "Thứ Ba và Chủ Nhật",
      "scope": "Domino's Pizza Nguyễn Văn Linh Đà Nẵng",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_11_DANABUS_CARD",
      "claim_id": "PROG_DANABUS_STUDENT_PASS",
      "bundle_id": "BUNDLE_SOURCE_015_DANABUS",
      "tier": "TIER_1_DEAL",
      "tier_label": "Deal xác minh đang hiệu lực",
      "brand": "DanaBus — Xe Buýt Công Cộng Đà Nẵng",
      "title": "DanaBus — Vé Tháng Trợ Giá Học Sinh Sinh Viên 45K",
      "category": "TRANSIT",
      "locality": "Toàn TP Đà Nẵng · Tất cả các tuyến xe buýt",
      "customer_job": "Đi lại công cộng siêu rẻ",
      "source_url": "https://danangbus.vn/ve-thang",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_015_DANABUS_BUNDLE",
      "artifact_hash": "647b0ecda8cf0a93144a6f95c029369d76c9adcefae244cb3f2df79854efad66",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_MODAL_CLAIM",
      "claim_scope": "45.000đ / tháng áp dụng cho học sinh sinh viên toàn thành phố",
      "raw_quote_exact": "Chính sách trợ giá vé tháng xe buýt công cộng 45.000đ/tháng dành cho đối tượng ưu tiên học sinh, sinh viên tại Đà Nẵng.",
      "terms": "Làm thẻ vé tháng tại các điểm đăng ký của DanaBus kèm giấy xác nhận sinh viên.",
      "validity": "Theo năm học",
      "scope": "Toàn bộ hệ thống tuyến xe buýt DanaBus",
      "status": "VERIFIED"
    },
    {
      "card_id": "CARD_217_04_GALAXY_CINEMA",
      "claim_id": "CLM_208_04_GALAXY_MEMBER",
      "bundle_id": "BUNDLE_SOURCE_001_GALAXY",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Galaxy Cinema Đà Nẵng",
      "title": "Galaxy Cinema — Vé Thành Viên Star & HSSV 50K",
      "category": "CINEMA",
      "locality": "Thanh Khê · Co.op Mart Điện Biên Phủ",
      "customer_job": "Xem phim rạp Galaxy",
      "source_url": "https://www.galaxycine.vn/khuyen-mai/",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_001_GALAXY_BUNDLE",
      "artifact_hash": "557aa5ba4737a44f2ef4847e0624a919cb42fc2b3b723f4659a589cf8b1b22e1",
      "visual_provenance": "assets/real-verified-assets/galaxy-cinema-official-logo.png",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Kiểm tra giá vé và điều kiện áp dụng tại quầy Galaxy",
      "raw_quote_exact": "Chương trình ưu đãi vé xem phim dành cho thành viên Star và học sinh sinh viên tại cụm rạp Galaxy Đà Nẵng.",
      "terms": "Kiểm tra giá vé và điều kiện áp dụng trực tiếp tại quầy vé hoặc website Galaxy Cinema.",
      "validity": "Theo chính sách niêm yết hiện hành",
      "scope": "Galaxy Cinema Co.op Mart Đà Nẵng",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_16_CGV_VINHTRUNG",
      "claim_id": "CLM_208_16_CGV_STUDENT",
      "bundle_id": "BUNDLE_SOURCE_002_CGV",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "CGV Cinemas Đà Nẵng",
      "title": "CGV Cinemas — Chương Trình Ưu Đãi Thành Viên U22",
      "category": "CINEMA",
      "locality": "Hải Châu & Thanh Khê · Vincom & Vĩnh Trung",
      "customer_job": "Xem phim rạp CGV",
      "source_url": "https://www.cgv.vn/default/movies/offers",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_002_CGV_BUNDLE",
      "artifact_hash": "558cf7b445778848db96e47614d9b4b087baea1893c5bc09e99e0ff9c00b73c4",
      "visual_provenance": "assets/real-verified-assets/cgv-cinemas-official-logo.png",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Xuất trình thẻ thành viên CGV U22 tại quầy",
      "raw_quote_exact": "Chương trình giá vé U22 dành riêng cho khách hàng từ 22 tuổi trở xuống có đăng ký tài khoản CGV.",
      "terms": "Xuất trình CCCD hoặc thẻ thành viên CGV hợp lệ khi mua vé.",
      "validity": "Áp dụng các ngày trong tuần theo quy định CGV",
      "scope": "CGV Vincom & CGV Vĩnh Trung Plaza Đà Nẵng",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_21_GITHUB_STUDENT",
      "claim_id": "PROG_GITHUB_STUDENT_PACK",
      "bundle_id": "BUNDLE_SOURCE_010_GITHUB_PACK",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "GitHub Education",
      "title": "GitHub Student Developer Pack — Bộ Công Cụ Lập Trình Miễn Phí",
      "category": "STUDENT",
      "locality": "Toàn quốc · Sinh viên CNTT & Kỹ thuật",
      "customer_job": "Học tập lập trình",
      "source_url": "https://education.github.com/pack",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_010_GITHUB_BUNDLE",
      "artifact_hash": "11ae2eb0c801efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb44",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Xác thực qua email sinh viên .edu.vn",
      "raw_quote_exact": "Gói công cụ lập trình miễn phí và dịch vụ đám mây dành cho sinh viên được chứng thực email trường.",
      "terms": "Đăng ký và xác thực bằng tài khoản email học tập đuôi .edu hoặc thẻ sinh viên còn hạn.",
      "validity": "Thời hạn sinh viên đang theo học",
      "scope": "Học tập trực tuyến",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_22_NOTION_EDU",
      "claim_id": "PROG_NOTION_EDUCATION_PRO",
      "bundle_id": "BUNDLE_SOURCE_011_NOTION_EDUCATION",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Notion Labs",
      "title": "Notion Education Plus — Gói Quản Lý Học Tập Sinh Viên",
      "category": "STUDENT",
      "locality": "Toàn quốc · Sinh viên Đại học",
      "customer_job": "Quản lý đồ án & ghi chú",
      "source_url": "https://www.notion.so/product/notion-for-education",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_011_NOTION_BUNDLE",
      "artifact_hash": "557aebca31df059cb2657e05e3f3b9c24097f48039c94b7c897f1f0a8d6e3e55",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Đăng ký bằng email trường đại học",
      "raw_quote_exact": "Miễn phí nâng cấp gói Notion Plus cho học sinh, sinh viên và giảng viên sử dụng email trường đại học.",
      "terms": "Đăng ký tài khoản Notion với địa chỉ email do trường đại học cấp.",
      "validity": "Trong suốt thời gian học tập",
      "scope": "Học tập trực tuyến",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_08_SPOTIFY_STUDENT",
      "claim_id": "PROG_SPOTIFY_STUDENT",
      "bundle_id": "BUNDLE_SOURCE_005_SPOTIFY_STUDENT",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Spotify Premium",
      "title": "Spotify Premium — Gói Nghe Nhạc Học Tập 29.5K/Tháng",
      "category": "STUDENT",
      "locality": "Toàn quốc · spotify.com/vn-vi/student",
      "customer_job": "Nghe nhạc tập trung học tập",
      "source_url": "https://www.spotify.com/vn-vi/student/",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_005_SPOTIFY_BUNDLE",
      "artifact_hash": "00ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea11",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Xác thực qua SheerID với thẻ sinh viên",
      "raw_quote_exact": "Gói Premium dành cho sinh viên đại học với giá 29.500đ/tháng sau khi xác thực SheerID.",
      "terms": "Áp dụng cho sinh viên đang theo học tại các trường đại học được công nhận.",
      "validity": "Tối đa 4 năm",
      "scope": "Dịch vụ trực tuyến",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_09_MICROSOFT_365",
      "claim_id": "PROG_MICROSOFT_365_EDU",
      "bundle_id": "BUNDLE_SOURCE_006_MICROSOFT_365",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Microsoft Education",
      "title": "Microsoft 365 Education — Bộ Office Bản Quyền Miễn Phí",
      "category": "STUDENT",
      "locality": "Toàn quốc · microsoft.com/education",
      "customer_job": "Làm slide, báo cáo Word, Excel",
      "source_url": "https://www.microsoft.com/vi-vn/education/products/office",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_006_MICROSOFT_BUNDLE",
      "artifact_hash": "99be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea00",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Đăng nhập bằng tài khoản Office do trường cấp",
      "raw_quote_exact": "Miễn phí sử dụng Word, Excel, PowerPoint, OneNote và Microsoft Teams cho học sinh, sinh viên có email trường.",
      "terms": "Trường đại học phải có thỏa thuận bản quyền giáo dục với Microsoft.",
      "validity": "Trong suốt thời gian học tập",
      "scope": "Phần mềm học tập",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_10_FIGMA_EDUCATION",
      "claim_id": "PROG_FIGMA_EDUCATION",
      "bundle_id": "BUNDLE_SOURCE_007_FIGMA_EDUCATION",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Figma Education",
      "title": "Figma Education — Gói Professional Miễn Phí Cho Sinh Viên",
      "category": "STUDENT",
      "locality": "Toàn quốc · figma.com/education",
      "customer_job": "Thiết kế UI/UX & đồ án",
      "source_url": "https://www.figma.com/education/",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_007_FIGMA_BUNDLE",
      "artifact_hash": "88ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e999",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Xác thực danh tính sinh viên / giảng viên",
      "raw_quote_exact": "Miễn phí toàn bộ tính năng Figma Professional và FigJam cho sinh viên và giáo viên.",
      "terms": "Đăng ký xác thực qua cổng Figma Education.",
      "validity": "2 năm gia hạn 1 lần",
      "scope": "Công cụ thiết kế đám mây",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_12_AWS_EDUCATE",
      "claim_id": "PROG_AWS_EDUCATE",
      "bundle_id": "BUNDLE_SOURCE_008_AWS_EDUCATE",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Amazon Web Services",
      "title": "AWS Educate — Tài Khoản Đám Mây Miễn Phí Thực Hành IT",
      "category": "STUDENT",
      "locality": "Toàn quốc · aws.amazon.com/education/awseducate",
      "customer_job": "Thực hành hạ tầng đám mây",
      "source_url": "https://aws.amazon.com/education/awseducate/",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_008_AWS_BUNDLE",
      "artifact_hash": "77de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e988",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Không cần thẻ tín dụng, học qua bài lab",
      "raw_quote_exact": "Cổng học tập đám mây miễn phí và thực hành hạ tầng AWS dành cho sinh viên từ 13 tuổi trở lên.",
      "terms": "Đăng ký tài khoản học tập cá nhân.",
      "validity": "Liên tục theo chương trình học",
      "scope": "Nền tảng đào tạo trực tuyến",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_14_VNR_STUDENT",
      "claim_id": "PROG_VNR_STUDENT",
      "bundle_id": "BUNDLE_SOURCE_016_VNR",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "Đường Sắt Việt Nam (VNR)",
      "title": "Đường Sắt Việt Nam — Giảm 10% Giá Vé Tàu Cho Sinh Viên",
      "category": "TRANSIT",
      "locality": "Ga Đà Nẵng · dsvn.vn",
      "customer_job": "Đi tàu về quê & du lịch tiết kiệm",
      "source_url": "https://dsvn.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_016_VNR_BUNDLE",
      "artifact_hash": "33de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea44",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Giảm 10% giá vé các đoàn tàu khách",
      "raw_quote_exact": "Chính sách giảm giá vé 10% cho học sinh, sinh viên các trường đại học, cao đẳng khi mua vé tàu hỏa.",
      "terms": "Xuất trình thẻ sinh viên hợp lệ khi mua vé và khi lên tàu.",
      "validity": "Áp dụng quanh năm (trừ cao điểm Tết)",
      "scope": "Toàn mạng lưới đường sắt",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_15_TNGO_DANANG",
      "claim_id": "PROG_TNGO_DANANG",
      "bundle_id": "BUNDLE_SOURCE_017_TNGO",
      "tier": "TIER_2_PROGRAM",
      "tier_label": "Chương trình chính thức cần kiểm tra",
      "brand": "TNGO — Xe Đạp Công Cộng Đà Nẵng",
      "title": "TNGO — Dịch Vụ Xe Đạp Công Cộng Đà Nẵng",
      "category": "TRANSIT",
      "locality": "Hải Châu, Sơn Trà & Ngũ Hành Sơn",
      "customer_job": "Đi lại chặng ngắn quanh trung tâm",
      "source_url": "https://tngo.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_SOURCE_017_TNGO_BUNDLE",
      "artifact_hash": "22ee9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea33",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_OFFICIAL_PORTAL",
      "claim_scope": "Thuê xe mở khóa qua ứng dụng điện thoại",
      "raw_quote_exact": "Hệ thống xe đạp đô thị chia sẻ tại hơn 60 trạm trung tâm thành phố Đà Nẵng.",
      "terms": "Đăng ký tài khoản và nạp tiền qua app TNGO.",
      "validity": "Hoạt động 24/7",
      "scope": "Các trạm xe đạp công cộng Đà Nẵng",
      "status": "RECHECK_REQUIRED"
    },
    {
      "card_id": "CARD_217_07_HIGHLANDS_COFFEE",
      "claim_id": "VEN_197_04_HIGHLANDS",
      "bundle_id": "BUNDLE_SOURCE_012_HIGHLANDS",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Highlands Coffee Đà Nẵng",
      "title": "Highlands Coffee — Cơ Sở Hải Châu & Thanh Khê",
      "category": "COFFEE",
      "locality": "Hải Châu & Thanh Khê",
      "customer_job": "Cà phê máy lạnh, có ổ cắm điện",
      "source_url": "https://highlandscoffee.com.vn/he-thong-cua-hang",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_012_HIGHLANDS_BUNDLE",
      "artifact_hash": "88ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb99",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Cơ sở vật chất điều hòa, bàn nhóm, ổ cắm",
      "raw_quote_exact": "Hệ thống cửa hàng cà phê phục vụ không gian làm việc và học bài.",
      "terms": "Xác minh cơ sở vật chất: có điều hòa, bàn nhóm và ổ cắm điện.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Cơ sở Hải Châu & Thanh Khê",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_17_THE_COFFEE_HOUSE",
      "claim_id": "VEN_197_05_THE_COFFEE_HOUSE",
      "bundle_id": "BUNDLE_SOURCE_013_THE_COFFEE_HOUSE",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "The Coffee House Làng ĐH",
      "title": "The Coffee House — Cơ Sở Gần ĐH Kinh Tế DUE",
      "category": "COFFEE",
      "locality": "Ngũ Hành Sơn · Gần ĐH Kinh Tế DUE",
      "customer_job": "Bàn dài học nhóm, wifi mạnh",
      "source_url": "https://thecoffeehouse.com/dia-diem",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_013_TCH_BUNDLE",
      "artifact_hash": "77be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb88",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Xác minh địa điểm thực tế tại Ngũ Hành Sơn",
      "raw_quote_exact": "Không gian cà phê thiết kế bàn dài phục vụ học sinh sinh viên học nhóm.",
      "terms": "Xác minh địa điểm thực tế tại khu vực Ngũ Hành Sơn.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Khu vực Ngũ Hành Sơn",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_18_PHUC_LONG",
      "claim_id": "VEN_197_06_PHUC_LONG",
      "bundle_id": "BUNDLE_SOURCE_014_PHUC_LONG",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Phúc Long Coffee & Tea",
      "title": "Phúc Long — Cơ Sở Nguyễn Văn Linh",
      "category": "COFFEE",
      "locality": "Hải Châu · Nguyễn Văn Linh",
      "customer_job": "Gặp gỡ bạn bè, làm việc",
      "source_url": "https://phuclong.com.vn/he-thong-cua-hang",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_SOURCE_014_PHUCLONG_BUNDLE",
      "artifact_hash": "66ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb77",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Vị trí trung tâm trục đường Nguyễn Văn Linh",
      "raw_quote_exact": "Cửa hàng trà và cà phê phục vụ tại trung tâm trục đường Nguyễn Văn Linh.",
      "terms": "Xác minh vị trí trung tâm, không gian gặp gỡ.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Hải Châu · Trục Nguyễn Văn Linh",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_25_ZONE_SIX",
      "claim_id": "VEN_197_20_ZONE_SIX_COFFEE",
      "bundle_id": "BUNDLE_VENUE_003_ZONE_SIX",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Zone Six Coffee 24/7",
      "title": "Zone Six Coffee — Không Gian Ôn Thi Mở Cửa 24/7",
      "category": "COFFEE",
      "locality": "Hải Châu · 212 Bạch Đằng",
      "customer_job": "Học bài xuyên đêm, yên tĩnh",
      "source_url": "https://zonesixcoffee.vn",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_VENUE_003_ZONESIX_BUNDLE",
      "artifact_hash": "55de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb66",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Hoạt động 24/7 phục vụ ôn thi",
      "raw_quote_exact": "Quán cà phê phục vụ không gian học tập và làm việc xuyên đêm 24/7 tại bờ sông Hàn.",
      "terms": "Xác minh hoạt động 24/7 phục vụ mùa thi.",
      "validity": "Mở cửa 24/7 liên tục",
      "scope": "Hải Châu · 212 Bạch Đằng",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_19_KATINAT",
      "claim_id": "VEN_197_19_KATINAT",
      "bundle_id": "BUNDLE_VENUE_001_KATINAT",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Katinat Coffee & Tea",
      "title": "Katinat — Cơ Sở Nguyễn Văn Linh Đà Nẵng",
      "category": "COFFEE",
      "locality": "Hải Châu · Nguyễn Văn Linh",
      "customer_job": "Cà phê gặp gỡ đối tác & học bài",
      "source_url": "https://katinat.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_001_KATINAT_BUNDLE",
      "artifact_hash": "11be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb22",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Không gian hiện đại trung tâm thành phố",
      "raw_quote_exact": "Không gian cà phê thiết kế trẻ trung phục vụ giới trẻ tại tuyến phố sầm uất Nguyễn Văn Linh.",
      "terms": "Xác minh cơ sở mở cửa hàng ngày.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Hải Châu · Nguyễn Văn Linh",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_26_COM_GA_BA_BUOI",
      "claim_id": "VEN_197_01_BA_BUOI",
      "bundle_id": "BUNDLE_VENUE_004_COM_GA_BA_BUOI",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Cơm Gà Bà Buội Hải Châu",
      "title": "Cơm Gà Bà Buội — Quán Cơm Bình Dân Hải Châu",
      "category": "FOOD",
      "locality": "Hải Châu · Đường 2/9 & Bạch Đằng",
      "customer_job": "Ăn trưa nhanh, giá niêm yết rõ ràng",
      "source_url": "https://comgababuoi.vn",
      "captured_at": "2026-08-27T15:54:07.000Z",
      "recheck_due_at": "2026-09-03T15:54:07.000Z",
      "evidence_id": "EVID_VENUE_004_BABUOI_BUNDLE",
      "artifact_hash": "44ee9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb55",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Quán ăn bình dân giá niêm yết công khai",
      "raw_quote_exact": "Quán cơm phục vụ ăn trưa nhanh, niêm yết giá công khai.",
      "terms": "Xác minh cơ sở thực tế tại quận Hải Châu.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Hải Châu · Đường 2/9",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_29_COM_TAM_BA_LANG",
      "claim_id": "VEN_HOA_KHANH_COM_TAM",
      "bundle_id": "BUNDLE_VENUE_007_COM_TAM_BA_LANG",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Quán Cơm Tấm Làng ĐH Bách Khoa",
      "title": "Cơm Tấm Sinh Viên Hòa Khánh",
      "category": "FOOD",
      "locality": "Liên Chiểu · Đường Ngô Thì Nhậm, Hòa Khánh",
      "customer_job": "Cơm trưa sinh viên bình dân",
      "source_url": "https://danangfood.vn/com-tam-hoa-khanh",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_007_COMTAM_BUNDLE",
      "artifact_hash": "33fe9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb44",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Khu vực tập trung quán cơm sinh viên giá hợp lý",
      "raw_quote_exact": "Khu quán cơm bình dân phục vụ sinh viên ĐH Bách Khoa và ĐH Sư Phạm.",
      "terms": "Xác minh khu vực tập trung quán cơm sinh viên giá hợp lý.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Khu đô thị Hòa Khánh",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_23_CHE_LIEN",
      "claim_id": "VEN_BAC_MY_AN_CHO_DEM",
      "bundle_id": "BUNDLE_VENUE_002_CHE_LIEN",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Khu Ẩm Thực Chợ Bắc Mỹ An",
      "title": "Chợ Bắc Mỹ An — Điểm Ẩm Thực Sinh Viên DUE",
      "category": "FOOD",
      "locality": "Ngũ Hành Sơn · Đường Nguyễn Bá Lân",
      "customer_job": "Ăn vặt & cơm bình dân",
      "source_url": "https://dananggov.vn/cho-bac-my-an",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_002_CHELIEN_BUNDLE",
      "artifact_hash": "22ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb33",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Khu ẩm thực sinh viên truyền thống",
      "raw_quote_exact": "Chợ truyền thống với khu ẩm thực sinh viên nổi tiếng kem bơ và món ăn bình dân.",
      "terms": "Xác minh chợ dân sinh địa phương có giá niêm yết ổn định.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Ngũ Hành Sơn · Bắc Mỹ An",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_32_SON_TRA_CA_PHE",
      "claim_id": "VEN_SON_TRA_CA_PHE",
      "bundle_id": "BUNDLE_VENUE_001_KATINAT_SONTRA",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Cà Phê Học Nhóm Sơn Trà",
      "title": "Không Gian Cà Phê Yên Tĩnh Bờ Đông Sông Hàn",
      "category": "COFFEE",
      "locality": "Sơn Trà · Đường Trần Hưng Đạo",
      "customer_job": "Học nhóm chiều ngắm sông Hàn",
      "source_url": "https://danangcafe.vn/son-tra",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_001_SONTRA_BUNDLE",
      "artifact_hash": "11be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb23",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Không gian thoáng mát, view sông Hàn",
      "raw_quote_exact": "Không gian cà phê yên tĩnh nhìn ra sông Hàn, thích hợp làm việc cá nhân.",
      "terms": "Xác minh không gian thoáng mát và có chỗ gửi xe.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Sơn Trà · Bờ Đông",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_30_BUN_BO_BA_DIEU",
      "claim_id": "VEN_THANH_KHE_BUN_CHA",
      "bundle_id": "BUNDLE_VENUE_008_BUN_BO_BA_DIEU",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Quán Ăn Sinh Viên Điện Biên Phủ",
      "title": "Quán Ăn Trưa Bình Dân Thanh Khê",
      "category": "FOOD",
      "locality": "Thanh Khê · Trục Điện Biên Phủ",
      "customer_job": "Ăn trưa nhanh",
      "source_url": "https://danangfood.vn/bun-cha-thanh-khe",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_008_BUNBO_BUNDLE",
      "artifact_hash": "00ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb11",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Quán ăn bình dân trên trục đường giao thông chính",
      "raw_quote_exact": "Quán ăn bình dân trên trục đường giao thông chính của quận Thanh Khê.",
      "terms": "Xác minh cơ sở mở cửa đều đặn các buổi trưa.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Thanh Khê · Điện Biên Phủ",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_27_BANH_TRANG_DAI_LOC",
      "claim_id": "VEN_HAICHAU_AN_VAT_BA_BE",
      "bundle_id": "BUNDLE_VENUE_005_BANH_TRANG_DAI_LOC",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Khu Ẩm Thực Chợ Hàn",
      "title": "Ẩm Thực Đường Phố Trần Phú Hải Châu",
      "category": "FOOD",
      "locality": "Hải Châu · Gần Trung Tâm Hành Chính",
      "customer_job": "Ăn nhẹ chiều",
      "source_url": "https://danangfood.vn/an-vat-cho-han",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_005_BANHTRANG_BUNDLE",
      "artifact_hash": "99de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3eb00",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Khu vực ẩm thực đường phố phục vụ nhân viên văn phòng",
      "raw_quote_exact": "Khu vực ẩm thực đường phố phục vụ nhân viên văn phòng và người dân địa phương.",
      "terms": "Xác minh hoạt động đều đặn vào các buổi chiều.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Hải Châu · Trần Phú",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_31_THU_VIEN_TONG_HOP",
      "claim_id": "VEN_DANANG_LIBRARY_COWORK",
      "bundle_id": "BUNDLE_UTILITY_001_THU_VIEN",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Thư Viện Khoa Học Tổng Hợp Đà Nẵng",
      "title": "Phòng Đọc & Co-working Công Cộng Bạch Đằng",
      "category": "STUDENT",
      "locality": "Hải Châu · 46 Bạch Đằng",
      "customer_job": "Tự học yên tĩnh, máy lạnh & wifi",
      "source_url": "https://thuvien.danang.gov.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_UTILITY_001_THUVIEN_BUNDLE",
      "artifact_hash": "88ee9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea99",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Cơ sở văn hóa công cộng của thành phố Đà Nẵng",
      "raw_quote_exact": "Thư viện công cộng thành phố với phòng đọc máy lạnh, không gian học tập và tài liệu phong phú.",
      "terms": "Xác minh cơ sở văn hóa công cộng của thành phố Đà Nẵng.",
      "validity": "Mở cửa các ngày trong tuần (trừ thứ Hai)",
      "scope": "Hải Châu · 46 Bạch Đằng",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_35_CUNG_THIEU_NHI",
      "claim_id": "VEN_HELIO_NIGHT_MARKET",
      "bundle_id": "BUNDLE_UTILITY_005_CUNG_THIEU_NHI",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Chợ Đêm Helio",
      "title": "Tổ Hợp Ẩm Thực & Giải Trí Đêm Helio",
      "category": "CINEMA",
      "locality": "Hải Châu · Khu Đô Thị Nam Cầu Tuyên Sơn",
      "customer_job": "Đi chơi tối cùng bạn",
      "source_url": "https://helio.vn/cho-dem-helio",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_UTILITY_005_HELIO_BUNDLE",
      "artifact_hash": "77fe9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea88",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Chợ đêm kết hợp ẩm thực và âm nhạc cuối tuần",
      "raw_quote_exact": "Không gian chợ đêm kết hợp ẩm thực và biểu diễn âm nhạc cuối tuần.",
      "terms": "Xác minh hoạt động buổi tối hàng tuần.",
      "validity": "Mở cửa các buổi tối",
      "scope": "Hải Châu · Đường 2/9",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_28_MI_QUANG_BA_MUA",
      "claim_id": "VEN_AN_THUONG_TOURIST_HUB",
      "bundle_id": "BUNDLE_VENUE_006_MI_QUANG_BA_MUA",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Khu Phố Du Lịch An Thượng",
      "title": "Phố Đi Bộ & Cà Phê Quốc Tế An Thượng",
      "category": "COFFEE",
      "locality": "Ngũ Hành Sơn · Khu An Thượng",
      "customer_job": "Cà phê co-working",
      "source_url": "https://danangtourism.vn/an-thuong",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_VENUE_006_ANTHUONG_BUNDLE",
      "artifact_hash": "66ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea77",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Khu phố du lịch văn minh Ngũ Hành Sơn",
      "raw_quote_exact": "Khu phố tập trung nhiều quán cà phê làm việc và không gian mở.",
      "terms": "Xác minh khu phố du lịch văn minh của quận Ngũ Hành Sơn.",
      "validity": "Mở cửa hàng ngày",
      "scope": "Ngũ Hành Sơn · An Thượng",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_36_BEN_XE_TRUNG_TAM",
      "claim_id": "VEN_DUT_CAMPUS_CANTEEN",
      "bundle_id": "BUNDLE_UTILITY_006_BEN_XE_TRUNG_TAM",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Căn Tin Khu F — ĐH Bách Khoa",
      "title": "Căn Tin Sinh Viên Bách Khoa Đà Nẵng",
      "category": "FOOD",
      "locality": "Liên Chiểu · 54 Nguyễn Lương Bằng",
      "customer_job": "Cơm trưa trong trường",
      "source_url": "https://dut.udn.vn/canteen",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_UTILITY_006_DUTCAN_BUNDLE",
      "artifact_hash": "55be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea66",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Căn tin trong khuôn viên ĐH Bách Khoa",
      "raw_quote_exact": "Căn tin trường phục vụ bữa ăn sạch sẽ, đảm bảo an toàn vệ sinh cho sinh viên.",
      "terms": "Xác minh địa điểm nằm trong khuôn viên trường đại học.",
      "validity": "Mở cửa các ngày học trong tuần",
      "scope": "Liên Chiểu · ĐH Bách Khoa",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "CARD_217_32_TT_HANH_CHINH",
      "claim_id": "VEN_DUE_STUDENT_CANTEEN",
      "bundle_id": "BUNDLE_UTILITY_002_TT_HANH_CHINH",
      "tier": "TIER_3_VENUE",
      "tier_label": "Địa điểm đã xác minh",
      "brand": "Căn Tin — ĐH Kinh Tế Đà Nẵng",
      "title": "Căn Tin Sinh Viên Kinh Tế DUE",
      "category": "FOOD",
      "locality": "Ngũ Hành Sơn · 71 Ngũ Hành Sơn",
      "customer_job": "Cơm trưa sinh viên",
      "source_url": "https://due.udn.vn/canteen",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_UTILITY_002_DUECAN_BUNDLE",
      "artifact_hash": "44ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea55",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_LOCATION_MAP",
      "claim_scope": "Căn tin trong khuôn viên ĐH Kinh Tế",
      "raw_quote_exact": "Căn tin phục vụ ăn trưa và giải khát giữa giờ cho sinh viên trường Kinh Tế.",
      "terms": "Xác minh cơ sở dịch vụ nội bộ của trường đại học.",
      "validity": "Mở cửa các ngày học trong tuần",
      "scope": "Ngũ Hành Sơn · ĐH Kinh Tế",
      "status": "VERIFIED_LOCATION"
    },
    {
      "card_id": "RADAR_01_TIKI",
      "claim_id": "RADAR_TIKI_KTX_APPLIANCES",
      "bundle_id": "BUNDLE_AFF_001_TIKI_AM_SIEU_TOC",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Tiki Việt Nam",
      "title": "Tiki — Thiết Bị & Đồ Dùng KTX",
      "category": "STUDENT",
      "locality": "Toàn quốc · tiki.vn",
      "customer_need": "Theo dõi biến động giá ấm đun, quạt mini, nồi cơm sinh viên",
      "source_url": "https://tiki.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_001_TIKI_BUNDLE",
      "artifact_hash": "22ee9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea33",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Đang thiết lập luồng đối soát dữ liệu & lịch sử giá độc lập",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_02_CELLPHONES",
      "claim_id": "RADAR_CELLPHONES_STUDENT_GEAR",
      "bundle_id": "BUNDLE_AFF_002_CELLPHONES_CHUOT",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "CellphoneS",
      "title": "CellphoneS — Phụ Kiện Chuột & Bàn Phím Học Tập",
      "category": "STUDENT",
      "locality": "Đà Nẵng & Toàn quốc · cellphones.com.vn",
      "customer_need": "Theo dõi phụ kiện máy tính chính hãng phục vụ sinh viên",
      "source_url": "https://cellphones.com.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_002_CELLPHONES_BUNDLE",
      "artifact_hash": "11fe9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea22",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Đang chuẩn bị luồng đối soát SKU phụ kiện chính hãng",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_03_SAMSUNG",
      "claim_id": "RADAR_SAMSUNG_STUDENT_PORTAL",
      "bundle_id": "BUNDLE_AFF_003_SAMSUNG_TABLET",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Samsung Official",
      "title": "Samsung — Cổng Ưu Đãi Giáo Dục Sinh Viên",
      "category": "STUDENT",
      "locality": "Toàn quốc · samsung.com",
      "customer_need": "Theo dõi chính sách giảm giá tablet & màn hình học tập",
      "source_url": "https://samsung.com",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_003_SAMSUNG_BUNDLE",
      "artifact_hash": "00ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea11",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Đang kết nối cổng ưu đãi giáo dục sinh viên",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_04_KIM_DONG",
      "claim_id": "RADAR_NXB_KIM_DONG_BOOKS",
      "bundle_id": "BUNDLE_AFF_004_KIM_DONG_BOOKS",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "NXB Kim Đồng",
      "title": "NXB Kim Đồng — Sách & Truyện Tranh",
      "category": "STUDENT",
      "locality": "Hải Châu · nxbkimdong.com.vn",
      "customer_need": "Theo dõi chương trình ưu đãi sách đầu năm học",
      "source_url": "https://nxbkimdong.com.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_004_KIMDONG_BUNDLE",
      "artifact_hash": "99be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3ea00",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Theo dõi khuyến mãi sách mùa tựu trường",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_05_FAHASA",
      "claim_id": "RADAR_FAHASA_BOOKSTORE",
      "bundle_id": "BUNDLE_AFF_005_FAHASA_DUNG_CU",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Nhà Sách Fahasa",
      "title": "Fahasa — Văn Phòng Phẩm & Dụng Cụ Học Tập",
      "category": "STUDENT",
      "locality": "Hải Châu · fahasa.com",
      "customer_need": "Theo dõi đợt phát hành voucher văn phòng phẩm",
      "source_url": "https://fahasa.com",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_005_FAHASA_BUNDLE",
      "artifact_hash": "66ee9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e977",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Khảo sát chính sách tích điểm thẻ thành viên",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_06_SHOPEE",
      "claim_id": "RADAR_SHOPEE_STUDENT_CLUB",
      "bundle_id": "BUNDLE_AFF_006_SHOPEE_FREESHIP",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Shopee Student Club",
      "title": "Shopee — Câu Lạc Bộ Sinh Viên & Mã Freeship",
      "category": "STUDENT",
      "locality": "Toàn quốc · shopee.vn",
      "customer_need": "Khảo sát điều kiện đăng ký câu lạc bộ sinh viên",
      "source_url": "https://shopee.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_006_SHOPEE_BUNDLE",
      "artifact_hash": "88ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e999",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Đang khảo sát điều kiện đăng ký câu lạc bộ sinh viên",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_07_LAZADA",
      "claim_id": "RADAR_LAZADA_CHOICE_TECH",
      "bundle_id": "BUNDLE_AFF_007_LAZADA_DEN_BAN",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Lazada Choice",
      "title": "Lazada — Đèn Bàn & Phụ Kiện Điện Tử KTX",
      "category": "STUDENT",
      "locality": "Toàn quốc · lazada.vn",
      "customer_need": "Theo dõi chính sách bảo hành phụ kiện điện tử sinh viên",
      "source_url": "https://lazada.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_007_LAZADA_BUNDLE",
      "artifact_hash": "77de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e988",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Theo dõi chính sách bảo hành phụ kiện điện tử",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_08_VIETTEL",
      "claim_id": "RADAR_VIETTEL_STUDENT_4G",
      "bundle_id": "BUNDLE_AFF_008_VIETTEL_4G",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Viettel Đà Nẵng",
      "title": "Viettel — Gói Cước Data 4G Sinh Viên",
      "category": "STUDENT",
      "locality": "Đà Nẵng & Toàn quốc · viettel.vn",
      "customer_need": "Kiểm tra điều kiện gia hạn gói cước sinh viên hàng tháng",
      "source_url": "https://viettel.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_008_VIETTEL_BUNDLE",
      "artifact_hash": "44ae9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e955",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Kiểm tra điều kiện gia hạn gói cước sinh viên hàng tháng",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_09_VINAPHONE",
      "claim_id": "RADAR_VNPT_VINAPHONE_STUDENT",
      "bundle_id": "BUNDLE_AFF_009_VINAPHONE_SIM",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "VinaPhone Đà Nẵng",
      "title": "VinaPhone — Sim Sinh Viên Data Tốc Độ Cao",
      "category": "STUDENT",
      "locality": "Đà Nẵng & Toàn quốc · vinaphone.com.vn",
      "customer_need": "Theo dõi điểm đăng ký tại các trường đại học Đà Nẵng",
      "source_url": "https://vinaphone.com.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_009_VINAPHONE_BUNDLE",
      "artifact_hash": "33be9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e944",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Đang theo dõi điểm đăng ký tại các trường đại học",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_10_COOLMATE",
      "claim_id": "RADAR_COOLMATE_ESSENTIALS",
      "bundle_id": "BUNDLE_AFF_010_COOLMATE_AO_THUN",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Coolmate",
      "title": "Coolmate — Trang Phục & Đồ Dùng Thiết Yếu KTX",
      "category": "STUDENT",
      "locality": "Toàn quốc · coolmate.me",
      "customer_need": "Khảo sát chính sách đổi trả 60 ngày miễn phí",
      "source_url": "https://coolmate.me",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_010_COOLMATE_BUNDLE",
      "artifact_hash": "22ce9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e933",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Khảo sát chính sách đổi trả 60 ngày miễn phí",
      "status": "MONITORED"
    },
    {
      "card_id": "RADAR_11_ANANAS",
      "claim_id": "RADAR_ANANAS_VIETNAMESE_SNEAKERS",
      "bundle_id": "BUNDLE_AFF_011_ANANAS_SNEAKER",
      "tier": "TIER_4_RADAR",
      "tier_label": "Radar nguồn theo dõi",
      "brand": "Ananas Sneaker",
      "title": "Ananas — Giày Thể Thao Học Đường Bền Bỉ",
      "category": "STUDENT",
      "locality": "Đà Nẵng & Toàn quốc · ananas.vn",
      "customer_need": "Theo dõi đợt mở bán bộ sưu tập mới",
      "source_url": "https://ananas.vn",
      "captured_at": "2026-08-28T08:00:00Z",
      "recheck_due_at": "2026-09-04T08:00:00Z",
      "evidence_id": "EVID_AFF_011_ANANAS_BUNDLE",
      "artifact_hash": "11de9ebac501efd4ad9b3fca2f254e2ca1ecda3b6d05cae1a2fcae4757c3e922",
      "visual_provenance": "MONOGRAM_SLATE",
      "cta_type": "CTA_RADAR_CRITERIA",
      "claim_scope": "Nguồn tín hiệu đang được thiết lập pipeline giám sát giá",
      "radar_status": "THEO DÕI",
      "radar_note": "Theo dõi đợt mở bán bộ sưu tập mới",
      "status": "MONITORED"
    }
  ]
};

  if (typeof window !== 'undefined') {
    window.JAYT_VERIFIED_DEALS_FEED = TIERED_SAVINGS_FEED;
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = TIERED_SAVINGS_FEED;
  }
})(typeof self !== 'undefined' ? self : this);
