/**
 * JAYT BATCH 02 INTAKE WORKER (EXECUTABLE RUNTIME PROCESS)
 * Governing Directive: JAYT-245 Section JAYT-260-CORRECTION-9 (Lines 5572-5586)
 *
 * CAPTURE-AGENT ENVELOPE CONTRACT:
 * 1. Untrusted CLI Metadata Forbidden: CLI --candidate-json is strictly FORBIDDEN (throws ERR_UNTRUSTED_CLI_METADATA_JSON_FORBIDDEN).
 * 2. Mandatory Verified Capture Envelope: Requires --envelope-file <path> generated by verified Capture Agent.
 * 3. Hash-Chain Signature Integrity: Verifies envelope_signature_hash across transport_receipt, raw_evidence, locator_replay, and capture_agent.agent_sha256.
 * 4. Gateway Raw Evidence Gate: Asserts non-quarantined status and verifies byte SHA-256 via jayt_canonical_admission_gateway.js.
 * 5. Fail-Closed Guarantee: Exits 1 on any failure, mismatch, tampered hash, or missing receipt; exits 0 only on fully verified envelope.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { verifyCandidateAdmission, readEvidenceFile } = require('../00_PROGRAM_BASELINE/jayt_canonical_admission_gateway.js');

const BATCH_NAMESPACE = "JAYT_MICRO_BATCH_02";

function computeEnvelopeSignatureHash(envelope) {
  const payload = JSON.stringify(envelope.transport_receipt) +
                  JSON.stringify(envelope.raw_evidence) +
                  JSON.stringify(envelope.locator_replay) +
                  envelope.capture_agent.agent_sha256;
  return crypto.createHash('sha256').update(payload).digest('hex');
}

function validateAndProcessCaptureEnvelope(envelopeFilePath) {
  const resolvedPath = path.resolve(envelopeFilePath);
  if (!fs.existsSync(resolvedPath)) {
    throw new Error('ERR_ENVELOPE_FILE_NOT_FOUND: ' + envelopeFilePath);
  }

  const rawEnvelope = fs.readFileSync(resolvedPath, 'utf8');
  let envelope;
  try {
    envelope = JSON.parse(rawEnvelope);
  } catch (err) {
    throw new Error('ERR_INVALID_ENVELOPE_JSON: ' + err.message);
  }

  // Schema Validation
  if (envelope.envelope_version !== 'CAP_AGENT_ENVELOPE_V1') {
    throw new Error('ERR_INVALID_ENVELOPE_VERSION: Expected CAP_AGENT_ENVELOPE_V1, got ' + envelope.envelope_version);
  }
  if (!envelope.capture_agent || !envelope.capture_agent.agent_sha256 || envelope.capture_agent.agent_sha256.length !== 64) {
    throw new Error('ERR_CAPTURE_AGENT_METADATA_MISSING: Missing or invalid capture_agent with 64-char agent_sha256.');
  }
  if (!envelope.transport_receipt || !envelope.transport_receipt.request_url || !envelope.transport_receipt.http_status) {
    throw new Error('ERR_TRANSPORT_RECEIPT_INCOMPLETE: Missing mandatory transport_receipt fields.');
  }
  if (!envelope.raw_evidence || !envelope.raw_evidence.raw_vault_path || !envelope.raw_evidence.raw_sha256) {
    throw new Error('ERR_RAW_EVIDENCE_INCOMPLETE: Missing raw_vault_path or raw_sha256 in raw_evidence.');
  }
  if (!Array.isArray(envelope.locator_replay) || envelope.locator_replay.length === 0) {
    throw new Error('ERR_LOCATOR_REPLAY_EMPTY: locator_replay must contain at least 1 verified locator.');
  }
  if (envelope.geographic_scope !== 'DA_NANG') {
    throw new Error('ERR_GEOGRAPHIC_SCOPE_VIOLATION: Candidate geographic scope must be DA_NANG.');
  }

  // Hash-Chain Signature Integrity Check
  const expectedSig = computeEnvelopeSignatureHash(envelope);
  if (envelope.envelope_signature_hash !== expectedSig) {
    throw new Error('ERR_ENVELOPE_SIGNATURE_HASH_TAMPERED: Declared signature ' + envelope.envelope_signature_hash + ' does not match computed hash-chain signature ' + expectedSig);
  }

  // Gateway Admission & Raw Bytes Check
  verifyCandidateAdmission(envelope, "INTAKE");
  const evidence = readEvidenceFile(envelope.raw_evidence.raw_vault_path, "INTAKE");
  if (evidence.sha256 !== envelope.raw_evidence.raw_sha256) {
    throw new Error('ERR_RAW_HASH_MISMATCH: Declared raw_sha256 does not match bytes on disk.');
  }

  const intakeRecord = {
    batch_namespace: BATCH_NAMESPACE,
    intake_timestamp_utc: new Date().toISOString(),
    candidate_id: envelope.candidate_id,
    title: envelope.title || envelope.candidate_id,
    geographic_scope: envelope.geographic_scope,
    envelope_version: envelope.envelope_version,
    capture_agent_name: envelope.capture_agent.name,
    capture_agent_version: envelope.capture_agent.version,
    transport_receipt: envelope.transport_receipt,
    raw_evidence: {
      raw_vault_path: envelope.raw_evidence.raw_vault_path,
      raw_sha256: evidence.sha256,
      byte_length: evidence.byteLength
    },
    locator_replay: envelope.locator_replay,
    envelope_signature_hash: envelope.envelope_signature_hash,
    intake_status: "RAW_CAPTURED",
    admission_state: "OPEN_EVALUATING",
    gateway_verified: true
  };

  return intakeRecord;
}

// CLI Execution Entrypoint
if (require.main === module) {
  const args = process.argv.slice(2);
  let envelopeFile = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--candidate-json') {
      console.error('INTAKE_WORKER_ERROR: ERR_UNTRUSTED_CLI_METADATA_JSON_FORBIDDEN: --candidate-json is forbidden in operational intake. Use --envelope-file with a signed Capture Agent envelope.');
      process.exit(1);
    } else if (args[i] === '--envelope-file' && args[i + 1]) {
      envelopeFile = args[i + 1];
      i++;
    }
  }

  if (!envelopeFile) {
    console.error('Usage: node run_batch_02_intake_worker.js --envelope-file <path>');
    process.exit(1);
  }

  try {
    const result = validateAndProcessCaptureEnvelope(envelopeFile);
    console.log(JSON.stringify(result, null, 2));
    process.exit(0);
  } catch (err) {
    console.error('INTAKE_WORKER_ERROR:', err.message);
    process.exit(1);
  }
}

module.exports = {
  validateAndProcessCaptureEnvelope,
  computeEnvelopeSignatureHash
};
