const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');

const REGISTRY_217 = {
  "registry_id": "JAYT_CARD_VISUAL_EVIDENCE_REGISTRY_217",
  "work_order": "JAYT-217-VISUAL-TRUTH-CONTRACT-STOP-SHIP-UNTIL-PROVEN",
  "version": "3.357.0",
  "updated_at": new Date().toISOString(),
  "dashboard_breakdown": {
    "total_cards": 29,
    "verified_exact_visuals_count": 0,
    "jayt_identity_visuals_count": 29,
    "blocked_assets_count": 0,
    "honest_summary": "Verified exact visuals: 0/29 · JayT identity visuals: 29/29 · Blocked assets: 0/29 (Chuẩn JAYT-217 Stop-Ship Contract)"
  },
  "cards": [
    // --- 12 BLUE OFFICIAL OFFERS -> IDENTITY_VISUAL ---
    {
      "card_id": "CARD_217_01_METIZ_MEMBER",
      "deal_id": "CLM_208_01_METIZ_MEMBER",
      "brand": "Metiz Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_METIZ_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #1E1B4B, #312E81)",
      "border_color": "#4338CA",
      "accent_color": "#A5B4FC",
      "tagline": "Rạp Phim Helio Center Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://metiz.vn/tin-va-khuyen-mai.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_02_METIZ_SUPER_MONDAY",
      "deal_id": "CLM_208_02_METIZ_SUPER_MONDAY",
      "brand": "Metiz Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_METIZ_02",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #1E1B4B, #312E81)",
      "border_color": "#4338CA",
      "accent_color": "#A5B4FC",
      "tagline": "Rạp Phim Helio Center Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://metiz.vn/tin-va-khuyen-mai.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_03_STARLIGHT_PROMO",
      "deal_id": "CLM_208_03_STARLIGHT_PROMO",
      "brand": "Starlight Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_STARLIGHT_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #78350F, #B45309)",
      "border_color": "#D97706",
      "accent_color": "#FDE68A",
      "tagline": "Cụm Rạp Điện Biên Phủ Thanh Khê",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://starlight.vn/uu-dai.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_04_STARLIGHT_TUE",
      "deal_id": "CLM_208_04_STARLIGHT_TUE",
      "brand": "Starlight Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_STARLIGHT_02",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #78350F, #B45309)",
      "border_color": "#D97706",
      "accent_color": "#FDE68A",
      "tagline": "Cụm Rạp Điện Biên Phủ Thanh Khê",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://starlight.vn/tin-tuc/thu-3-phim-viet.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_05_DOMINOS_DISCOUNT",
      "deal_id": "CLM_208_05_DOMINOS_DISCOUNT",
      "brand": "Domino's Pizza",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_DOMINOS_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "DOM",
      "theme_gradient": "linear-gradient(135deg, #0C4A6E, #0284C7)",
      "border_color": "#0284C7",
      "accent_color": "#BAE6FD",
      "tagline": "Domino's Pizza Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://dominos.vn/khuyen-mai",
      "asset_sha256": null,
      "brand_and_branch_relation": "Domino's Pizza - Nguyễn Văn Linh & Hùng Vương, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_06_POPEYES_PROMO",
      "deal_id": "CLM_208_06_POPEYES_PROMO",
      "brand": "Popeyes Louisiana Kitchen",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_POPEYES_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "POP",
      "theme_gradient": "linear-gradient(135deg, #7C2D12, #EA580C)",
      "border_color": "#EA580C",
      "accent_color": "#FED7AA",
      "tagline": "Popeyes Louisiana Kitchen Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://popeyes.vn/khuyen-mai",
      "asset_sha256": null,
      "brand_and_branch_relation": "Popeyes Louisiana Kitchen - Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_07_GALAXY_MOVIE",
      "deal_id": "CLM_208_07_GALAXY_MOVIE",
      "brand": "Galaxy Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_GALAXY_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "GLX",
      "theme_gradient": "linear-gradient(135deg, #1E293B, #0284C7)",
      "border_color": "#0284C7",
      "accent_color": "#38BDF8",
      "tagline": "Galaxy Cinema Coop Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://galaxycine.vn/khuyen-mai",
      "asset_sha256": null,
      "brand_and_branch_relation": "Galaxy Cinema - Tầng 1 Siêu thị Co.opmart, 478 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_08_SPOTIFY_STUDENT",
      "deal_id": "CLM_208_08_SPOTIFY_STUDENT",
      "brand": "Spotify Vietnam",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_SPOTIFY_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "SPT",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #10B981)",
      "border_color": "#10B981",
      "accent_color": "#6EE7B7",
      "tagline": "Spotify Premium Sinh Viên",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.spotify.com/vn-vi/student/",
      "asset_sha256": null,
      "brand_and_branch_relation": "Spotify Student Program - Xác thực sinh viên các trường ĐH Đà Nẵng qua SheerID",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_09_MICROSOFT_365",
      "deal_id": "CLM_208_09_MICROSOFT_365",
      "brand": "Microsoft Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_MSFT_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "MSF",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #2563EB)",
      "border_color": "#2563EB",
      "accent_color": "#93C5FD",
      "tagline": "Microsoft Student & Education",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.microsoft.com/vi-vn/education/products/office",
      "asset_sha256": null,
      "brand_and_branch_relation": "Microsoft Education - Xác thực email trường .edu.vn (BK, SP, DUE, FPT, VKU ĐN)",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_10_FIGMA_EDUCATION",
      "deal_id": "CLM_208_10_FIGMA_EDUCATION",
      "brand": "Figma for Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_FIGMA_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "FIG",
      "theme_gradient": "linear-gradient(135deg, #18181B, #3F3F46)",
      "border_color": "#71717A",
      "accent_color": "#A78BFA",
      "tagline": "Figma for Education",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.figma.com/education/",
      "asset_sha256": null,
      "brand_and_branch_relation": "Figma Education Program - Dành cho sinh viên các trường ĐH tại Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_11_AUTODESK_EDU",
      "deal_id": "CLM_208_11_AUTODESK_EDU",
      "brand": "Autodesk Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_AUTODESK_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "ADK",
      "theme_gradient": "linear-gradient(135deg, #0F172A, #0EA5E9)",
      "border_color": "#0EA5E9",
      "accent_color": "#BAE6FD",
      "tagline": "Autodesk Education Downloads",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.autodesk.com/education/edu-software/overview",
      "asset_sha256": null,
      "brand_and_branch_relation": "Autodesk Education Community - Sinh viên kỹ thuật, kiến trúc ĐH Bách Khoa ĐN",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_12_AWS_EDUCATE",
      "deal_id": "CLM_208_12_AWS_EDUCATE",
      "brand": "Amazon Web Services",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_IDENT_AWS_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "AWS",
      "theme_gradient": "linear-gradient(135deg, #1C1917, #D97706)",
      "border_color": "#D97706",
      "accent_color": "#FDE68A",
      "tagline": "AWS Educate Cloud Skills",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://aws.amazon.com/education/awseducate/",
      "asset_sha256": null,
      "brand_and_branch_relation": "AWS Educate Student Portal - Sinh viên CNTT các trường Đại học Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },

    // --- 17 PURPLE VERIFIED VENUES -> IDENTITY_VISUAL ---
    {
      "card_id": "CARD_217_13_METIZ_HELIO",
      "deal_id": "CLM_208_13_METIZ_HELIO",
      "brand": "Metiz Cinema Helio",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_METIZ_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #0F172A, #4338CA)",
      "border_color": "#4338CA",
      "accent_color": "#818CF8",
      "tagline": "Rạp Phim Helio Center Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://metiz.vn/rap-va-gia-ve.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_14_STARLIGHT_NK",
      "deal_id": "CLM_208_14_STARLIGHT_NK",
      "brand": "Starlight Cinema Nguyễn Kim",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_STARLIGHT_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #3B1C08, #D97706)",
      "border_color": "#D97706",
      "accent_color": "#FCD34D",
      "tagline": "Cụm Rạp Điện Biên Phủ Thanh Khê",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://starlight.vn/rap/da-nang.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_15_GALAXY_DANANG",
      "deal_id": "CLM_208_15_GALAXY_DANANG",
      "brand": "Galaxy Cinema Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_GALAXY_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "GLX",
      "theme_gradient": "linear-gradient(135deg, #0B1E36, #0284C7)",
      "border_color": "#0284C7",
      "accent_color": "#7DD3FC",
      "tagline": "Galaxy Cinema Coop Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://galaxycine.vn/rap-gia-ve/galaxy-da-nang",
      "asset_sha256": null,
      "brand_and_branch_relation": "Galaxy Cinema - Tầng 1 TTTM Co.opmart, 478 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_16_CGV_VINHTRUNG",
      "deal_id": "CLM_208_16_CGV_VINHTRUNG",
      "brand": "CGV Vĩnh Trung Plaza",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_CGV_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "CGV",
      "theme_gradient": "linear-gradient(135deg, #450A0A, #DC2626)",
      "border_color": "#DC2626",
      "accent_color": "#FECACA",
      "tagline": "CGV Cinemas Vĩnh Trung Plaza",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.cgv.vn/default/cinox/site/cgv-vinh-trung-plaza",
      "asset_sha256": null,
      "brand_and_branch_relation": "CGV Cinemas - Tầng 3 Vĩnh Trung Plaza, 255-257 Hùng Vương, Thanh Khê, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_17_HIGHLANDS_DN",
      "deal_id": "CLM_208_17_HIGHLANDS_DN",
      "brand": "Highlands Coffee Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_HIGHLANDS_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "HLC",
      "theme_gradient": "linear-gradient(135deg, #431407, #9A3412)",
      "border_color": "#9A3412",
      "accent_color": "#FED7AA",
      "tagline": "Highlands Coffee Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.highlandscoffee.com.vn/vn/he-thong-cua-hang.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Highlands Coffee - Chi nhánh Nguyễn Văn Linh & Bạch Đằng, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_18_TCH_DANANG",
      "deal_id": "CLM_208_18_TCH_DANANG",
      "brand": "The Coffee House",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_TCH_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "TCH",
      "theme_gradient": "linear-gradient(135deg, #7C2D12, #EA580C)",
      "border_color": "#EA580C",
      "accent_color": "#FFEDD5",
      "tagline": "The Coffee House Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://thecoffeehouse.com/pages/danh-sach-cua-hang",
      "asset_sha256": null,
      "brand_and_branch_relation": "The Coffee House - 461 Trần Hưng Đạo & 80 Nguyễn Văn Linh, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_19_PHUCLONG_DN",
      "deal_id": "CLM_208_19_PHUCLONG_DN",
      "brand": "Phúc Long Coffee & Tea",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_PHUCLONG_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "PLG",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #059669)",
      "border_color": "#059669",
      "accent_color": "#A7F3D0",
      "tagline": "Phúc Long Coffee & Tea Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://phuclong.com.vn/he-thong-cua-hang-phuc-long",
      "asset_sha256": null,
      "brand_and_branch_relation": "Phúc Long Coffee & Tea - 61 Nguyễn Văn Linh & TTTM Vincom Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_20_KATINAT_DN",
      "deal_id": "CLM_208_20_KATINAT_DN",
      "brand": "Katinat Saigon Kafe",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_KATINAT_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "KTN",
      "theme_gradient": "linear-gradient(135deg, #1C1917, #78716C)",
      "border_color": "#78716C",
      "accent_color": "#E7E5E4",
      "tagline": "Katinat Saigon Kafe Bạch Đằng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://katinat.vn/danh-sach-cua-hang",
      "asset_sha256": null,
      "brand_and_branch_relation": "Katinat Saigon Kafe - 16 Bạch Đằng, P. Thạch Thang, Q. Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_21_COMGA_BABUOI",
      "deal_id": "CLM_208_21_COMGA_BABUOI",
      "brand": "Cơm Gà Bà Buội Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_COMGA_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "CGB",
      "theme_gradient": "linear-gradient(135deg, #713F12, #CA8A04)",
      "border_color": "#CA8A04",
      "accent_color": "#FEF08A",
      "tagline": "Cơm Gà Bà Buội Chi Nhánh Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.facebook.com/comgababuoi.danang/",
      "asset_sha256": null,
      "brand_and_branch_relation": "Cơm Gà Bà Buội - 253 Hồ Nghinh, P. Phước Mỹ, Q. Sơn Trà, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_22_BANHTRANG_DAILOC",
      "deal_id": "CLM_208_22_BANHTRANG_DAILOC",
      "brand": "Bánh Tráng Thịt Heo Đại Lộc",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_BANHTRANG_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "BTĐ",
      "theme_gradient": "linear-gradient(135deg, #3F6212, #65A30D)",
      "border_color": "#65A30D",
      "accent_color": "#D9F99D",
      "tagline": "Bánh Tráng Thịt Heo Đại Lộc",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://maps.google.com/?cid=banhtrangdailocdanang",
      "asset_sha256": null,
      "brand_and_branch_relation": "Bánh Tráng Đại Lộc - 97 Trưng Nữ Vương, P. Bình Hiên, Q. Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_23_DANABUS_PUBLIC",
      "deal_id": "CLM_208_23_DANABUS_PUBLIC",
      "brand": "Xe Buýt Danabus Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_DANABUS_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "DNB",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #059669)",
      "border_color": "#059669",
      "accent_color": "#6EE7B7",
      "tagline": "Hệ Thống Xe Buýt Nội Đô Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://danabus.vn/he-thong-tuyen.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Danabus - 497 Bùi Thị Xuân, Sơn Trà & Toàn bộ mạng lưới tuyến nội đô Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_24_DVC_DANANG",
      "deal_id": "CLM_208_24_DVC_DANANG",
      "brand": "Cổng Dịch Vụ Công Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_VENUE_DVC_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "DVC",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #2563EB)",
      "border_color": "#2563EB",
      "accent_color": "#BFDBFE",
      "tagline": "Cổng Dịch Vụ Công TP Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://dichvucong.danang.gov.vn",
      "asset_sha256": null,
      "brand_and_branch_relation": "Trung Tâm Hành Chính & Cổng Dịch Vụ Công TP Đà Nẵng, 24 Trần Phú, Hải Châu",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_25_MIQUANG_BAMUA",
      "deal_id": "CLM_208_25_MIQUANG_BAMUA",
      "brand": "Mì Quảng Bà Mua",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_MIQUANG_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "MQM",
      "theme_gradient": "linear-gradient(135deg, #713F12, #A16207)",
      "border_color": "#A16207",
      "accent_color": "#FDE68A",
      "tagline": "Mì Quảng Bà Mua Đà Nẵng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.facebook.com/miquangbamuadanang/",
      "asset_sha256": null,
      "brand_and_branch_relation": "Mì Quảng Bà Mua - Trần Bình Trọng / Đống Đa, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_26_HELIO_NIGHT",
      "deal_id": "CLM_208_26_HELIO_NIGHT",
      "brand": "Chợ Đêm Helio",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_HELIO_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "HLN",
      "theme_gradient": "linear-gradient(135deg, #831843, #BE185D)",
      "border_color": "#BE185D",
      "accent_color": "#FBCFE8",
      "tagline": "Chợ Đêm Helio Center",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://helio.vn/cho-dem-helio.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Chợ Đêm Helio - Khuôn viên Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_27_SONTRA_NIGHT",
      "deal_id": "CLM_208_27_SONTRA_NIGHT",
      "brand": "Chợ Đêm Sơn Trà",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_SONTRA_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "STN",
      "theme_gradient": "linear-gradient(135deg, #4C1D95, #7C3AED)",
      "border_color": "#7C3AED",
      "accent_color": "#DDD6FE",
      "tagline": "Chợ Đêm Cầu Rồng Sơn Trà",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://danangfantasticity.com/cho-dem-son-tra",
      "asset_sha256": null,
      "brand_and_branch_relation": "Chợ Đêm Sơn Trà - Mai Hắc Đế & Lý Nam Đế, An Hải Tây, Sơn Trà, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_28_UDN_STUDENT_CENTER",
      "deal_id": "CLM_208_28_UDN_STUDENT_CENTER",
      "brand": "Trung Tâm Hỗ Trợ Sinh Viên ĐH Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_UDN_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "UDN",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #3B82F6)",
      "border_color": "#3B82F6",
      "accent_color": "#BFDBFE",
      "tagline": "Trung Tâm Hỗ Trợ Sinh Viên ĐHĐN",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://udn.vn/ban-cong-tac-hoc-sinh-sinh-vien",
      "asset_sha256": null,
      "brand_and_branch_relation": "Trung Tâm Hỗ Trợ Sinh Viên ĐHĐN - 41 Lê Duẩn, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_217_29_PUBLIC_SERVICES",
      "deal_id": "CLM_208_29_PUBLIC_SERVICES",
      "brand": "Thư Viện Tổng Hợp Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_LIBRARY_01",
      "visual_kind": "IDENTITY_VISUAL",
      "monogram": "TVT",
      "theme_gradient": "linear-gradient(135deg, #0F766E, #0D9488)",
      "border_color": "#0D9488",
      "accent_color": "#99F6E4",
      "tagline": "Thư Viện Khoa Học 46 Bạch Đằng",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://thuvien.danang.gov.vn",
      "asset_sha256": null,
      "brand_and_branch_relation": "Thư Viện Khoa Học Tổng Hợp Đà Nẵng - 46 Bạch Đằng, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_217.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu JayT — chưa có ảnh ưu đãi/địa điểm xác minh"
    }
  ]
};

const sotRegistryPath = path.join(repoRoot, '03_SOURCE_OF_TRUTH', 'card_visual_evidence_registry.json');
fs.writeFileSync(sotRegistryPath, JSON.stringify(REGISTRY_217, null, 2), 'utf8');

const qaRegistryPath = path.join(repoRoot, '07_QUALITY_ASSURANCE', 'runtime_evidence', 'card_visual_evidence_registry_217.json');
fs.writeFileSync(qaRegistryPath, JSON.stringify(REGISTRY_217, null, 2), 'utf8');

console.log('✅ Card Visual Evidence Registry 217 successfully written to SOT and QA runtime evidence.');
