const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const repoRoot = path.resolve(__dirname, '..');
const manifestPath = path.join(repoRoot, '03_SOURCE_OF_TRUTH', 'assets', 'official-visuals', 'ASSETS_MANIFEST_215.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

function findManifestItem(fileName) {
  return manifest.find(m => m.file_name === fileName) || null;
}

const REGISTRY_215 = {
  "registry_id": "JAYT_CARD_VISUAL_EVIDENCE_REGISTRY_215",
  "work_order": "JAYT-215-REAL-VISUAL-SUPPLY-SPRINT",
  "version": "3.355.0",
  "updated_at": new Date().toISOString(),
  "dashboard_breakdown": {
    "total_cards": 29,
    "visual_ui_coverage": "29/29 (100.0%)",
    "exact_promotion_visual_count": 12,
    "exact_venue_visual_count": 12,
    "official_identity_visual_count": 5,
    "neutral_fallback_count": 0,
    "honest_summary": "12 Exact Promotion Visuals (100% nhóm ưu đãi) + 12 Exact Venue Visuals (70.6% nhóm địa điểm) + 5 Identity Canvases"
  },
  "cards": [
    // --- 12 BLUE OFFICIAL OFFERS -> EXACT_PROMOTION ---
    {
      "card_id": "CARD_215_01_METIZ_MEMBER",
      "deal_id": "CLM_208_01_METIZ_MEMBER",
      "brand": "Metiz Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_METIZ_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #0F172A, #312E81)",
      "border_color": "#4338CA",
      "asset_file_or_embed_url": "assets/official-visuals/promo-metiz-member.png",
      "source_page_url": "https://metiz.vn/tin-va-khuyen-mai.html",
      "asset_sha256": findManifestItem('promo-metiz-member.png').sha256,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_02_METIZ_SUPER_MONDAY",
      "deal_id": "CLM_208_02_METIZ_SUPER_MONDAY",
      "brand": "Metiz Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_METIZ_02",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #1E1B4B, #4F46E5)",
      "border_color": "#4338CA",
      "asset_file_or_embed_url": "assets/official-visuals/promo-metiz-super-monday.png",
      "source_page_url": "https://metiz.vn/tin-va-khuyen-mai.html",
      "asset_sha256": findManifestItem('promo-metiz-super-monday.png').sha256,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_03_STARLIGHT_PROMO",
      "deal_id": "CLM_208_03_STARLIGHT_PROMO",
      "brand": "Starlight Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_STARLIGHT_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #451A03, #B45309)",
      "border_color": "#D97706",
      "asset_file_or_embed_url": "assets/official-visuals/promo-starlight-member.png",
      "source_page_url": "https://starlight.vn/uu-dai.html",
      "asset_sha256": findManifestItem('promo-starlight-member.png').sha256,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_04_STARLIGHT_TUE",
      "deal_id": "CLM_208_04_STARLIGHT_TUE",
      "brand": "Starlight Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_STARLIGHT_02",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #78350F, #C2410C)",
      "border_color": "#D97706",
      "asset_file_or_embed_url": "assets/official-visuals/promo-starlight-viet-phim.png",
      "source_page_url": "https://starlight.vn/tin-tuc/thu-3-phim-viet.html",
      "asset_sha256": findManifestItem('promo-starlight-viet-phim.png').sha256,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_05_DOMINOS_DISCOUNT",
      "deal_id": "CLM_208_05_DOMINOS_DISCOUNT",
      "brand": "Domino's Pizza",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_DOMINOS_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "DOM",
      "theme_gradient": "linear-gradient(135deg, #0C4A6E, #0284C7)",
      "border_color": "#0284C7",
      "asset_file_or_embed_url": "assets/official-visuals/promo-dominos-bogo.png",
      "source_page_url": "https://dominos.vn/khuyen-mai",
      "asset_sha256": findManifestItem('promo-dominos-bogo.png').sha256,
      "brand_and_branch_relation": "Domino's Pizza - Nguyễn Văn Linh & Hùng Vương, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_06_POPEYES_PROMO",
      "deal_id": "CLM_208_06_POPEYES_PROMO",
      "brand": "Popeyes Louisiana Kitchen",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_POPEYES_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "POP",
      "theme_gradient": "linear-gradient(135deg, #7C2D12, #EA580C)",
      "border_color": "#EA580C",
      "asset_file_or_embed_url": "assets/official-visuals/promo-popeyes-chicken.png",
      "source_page_url": "https://popeyes.vn/khuyen-mai",
      "asset_sha256": findManifestItem('promo-popeyes-chicken.png').sha256,
      "brand_and_branch_relation": "Popeyes Louisiana Kitchen - Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_07_GALAXY_MOVIE",
      "deal_id": "CLM_208_07_GALAXY_MOVIE",
      "brand": "Galaxy Cinema Đà Nẵng",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_GALAXY_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "GLX",
      "theme_gradient": "linear-gradient(135deg, #1E293B, #0284C7)",
      "border_color": "#0284C7",
      "asset_file_or_embed_url": "assets/official-visuals/promo-galaxy-happy-day.png",
      "source_page_url": "https://galaxycine.vn/khuyen-mai",
      "asset_sha256": findManifestItem('promo-galaxy-happy-day.png').sha256,
      "brand_and_branch_relation": "Galaxy Cinema - Tầng 1 Siêu thị Co.opmart, 478 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_08_SPOTIFY_STUDENT",
      "deal_id": "CLM_208_08_SPOTIFY_STUDENT",
      "brand": "Spotify Vietnam",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_SPOTIFY_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "SPT",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #10B981)",
      "border_color": "#10B981",
      "asset_file_or_embed_url": "assets/official-visuals/promo-spotify-student.png",
      "source_page_url": "https://www.spotify.com/vn-vi/student/",
      "asset_sha256": findManifestItem('promo-spotify-student.png').sha256,
      "brand_and_branch_relation": "Spotify Student Program - Xác thực sinh viên các trường ĐH Đà Nẵng qua SheerID",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_09_MICROSOFT_365",
      "deal_id": "CLM_208_09_MICROSOFT_365",
      "brand": "Microsoft Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_MSFT_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "MSF",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #2563EB)",
      "border_color": "#2563EB",
      "asset_file_or_embed_url": "assets/official-visuals/promo-microsoft-365-student.png",
      "source_page_url": "https://www.microsoft.com/vi-vn/education/products/office",
      "asset_sha256": findManifestItem('promo-microsoft-365-student.png').sha256,
      "brand_and_branch_relation": "Microsoft Education - Xác thực email trường .edu.vn (BK, SP, DUE, FPT, VKU ĐN)",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_10_FIGMA_EDUCATION",
      "deal_id": "CLM_208_10_FIGMA_EDUCATION",
      "brand": "Figma for Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_FIGMA_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "FIG",
      "theme_gradient": "linear-gradient(135deg, #18181B, #3F3F46)",
      "border_color": "#71717A",
      "asset_file_or_embed_url": "assets/official-visuals/promo-figma-education.png",
      "source_page_url": "https://www.figma.com/education/",
      "asset_sha256": findManifestItem('promo-figma-education.png').sha256,
      "brand_and_branch_relation": "Figma Education Program - Dành cho sinh viên các trường ĐH tại Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_11_AUTODESK_EDU",
      "deal_id": "CLM_208_11_AUTODESK_EDU",
      "brand": "Autodesk Education",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_AUTODESK_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "ADK",
      "theme_gradient": "linear-gradient(135deg, #0F172A, #0EA5E9)",
      "border_color": "#0EA5E9",
      "asset_file_or_embed_url": "assets/official-visuals/promo-autodesk-education.png",
      "source_page_url": "https://www.autodesk.com/education/edu-software/overview",
      "asset_sha256": findManifestItem('promo-autodesk-education.png').sha256,
      "brand_and_branch_relation": "Autodesk Education Community - Sinh viên kỹ thuật, kiến trúc ĐH Bách Khoa ĐN",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },
    {
      "card_id": "CARD_215_12_AWS_EDUCATE",
      "deal_id": "CLM_208_12_AWS_EDUCATE",
      "brand": "Amazon Web Services",
      "tier": "TIER_BLUE_OFFICIAL",
      "visual_asset_id": "ASSET_EXACT_PROMO_AWS_01",
      "visual_kind": "EXACT_PROMOTION",
      "monogram": "AWS",
      "theme_gradient": "linear-gradient(135deg, #1C1917, #D97706)",
      "border_color": "#D97706",
      "asset_file_or_embed_url": "assets/official-visuals/promo-aws-educate.png",
      "source_page_url": "https://aws.amazon.com/education/awseducate/",
      "asset_sha256": findManifestItem('promo-aws-educate.png').sha256,
      "brand_and_branch_relation": "AWS Educate Student Portal - Sinh viên CNTT các trường Đại học Đà Nẵng",
      "rights_basis": "OFFICIAL_PROMOTION_PROGRAM_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-03T10:54:05.524Z",
      "render_label": "Ảnh/banner khuyến mãi chính thức (Khớp SHA-256)"
    },

    // --- 12 PURPLE VERIFIED VENUES -> EXACT_VENUE ---
    {
      "card_id": "CARD_215_13_METIZ_HELIO",
      "deal_id": "CLM_208_13_METIZ_HELIO",
      "brand": "Metiz Cinema Helio",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_METIZ_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "MTZ",
      "theme_gradient": "linear-gradient(135deg, #0F172A, #4338CA)",
      "border_color": "#4338CA",
      "asset_file_or_embed_url": "assets/official-visuals/venue-metiz-helio-danang.png",
      "source_page_url": "https://metiz.vn/rap-va-gia-ve.html",
      "asset_sha256": findManifestItem('venue-metiz-helio-danang.png').sha256,
      "brand_and_branch_relation": "Metiz Cinema - Tầng 1 Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_14_STARLIGHT_NK",
      "deal_id": "CLM_208_14_STARLIGHT_NK",
      "brand": "Starlight Cinema Nguyễn Kim",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_STARLIGHT_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "STL",
      "theme_gradient": "linear-gradient(135deg, #3B1C08, #D97706)",
      "border_color": "#D97706",
      "asset_file_or_embed_url": "assets/official-visuals/venue-starlight-nguyenkim-danang.png",
      "source_page_url": "https://starlight.vn/rap/da-nang.html",
      "asset_sha256": findManifestItem('venue-starlight-nguyenkim-danang.png').sha256,
      "brand_and_branch_relation": "Starlight Cinema - Tầng 3-4 TTTM Nguyễn Kim, 46 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_15_GALAXY_DANANG",
      "deal_id": "CLM_208_15_GALAXY_DANANG",
      "brand": "Galaxy Cinema Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_GALAXY_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "GLX",
      "theme_gradient": "linear-gradient(135deg, #0B1E36, #0284C7)",
      "border_color": "#0284C7",
      "asset_file_or_embed_url": "assets/official-visuals/venue-galaxy-coopmart-danang.png",
      "source_page_url": "https://galaxycine.vn/rap-gia-ve/galaxy-da-nang",
      "asset_sha256": findManifestItem('venue-galaxy-coopmart-danang.png').sha256,
      "brand_and_branch_relation": "Galaxy Cinema - Tầng 1 TTTM Co.opmart, 478 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_16_CGV_VINHTRUNG",
      "deal_id": "CLM_208_16_CGV_VINHTRUNG",
      "brand": "CGV Vĩnh Trung Plaza",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_CGV_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "CGV",
      "theme_gradient": "linear-gradient(135deg, #450A0A, #DC2626)",
      "border_color": "#DC2626",
      "asset_file_or_embed_url": "assets/official-visuals/venue-cgv-vinhtrung-danang.png",
      "source_page_url": "https://www.cgv.vn/default/cinox/site/cgv-vinh-trung-plaza",
      "asset_sha256": findManifestItem('venue-cgv-vinhtrung-danang.png').sha256,
      "brand_and_branch_relation": "CGV Cinemas - Tầng 3 Vĩnh Trung Plaza, 255-257 Hùng Vương, Thanh Khê, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_17_HIGHLANDS_DN",
      "deal_id": "CLM_208_17_HIGHLANDS_DN",
      "brand": "Highlands Coffee Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_HIGHLANDS_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "HLC",
      "theme_gradient": "linear-gradient(135deg, #431407, #9A3412)",
      "border_color": "#9A3412",
      "asset_file_or_embed_url": "assets/official-visuals/venue-highlands-danang.png",
      "source_page_url": "https://www.highlandscoffee.com.vn/vn/he-thong-cua-hang.html",
      "asset_sha256": findManifestItem('venue-highlands-danang.png').sha256,
      "brand_and_branch_relation": "Highlands Coffee - Chi nhánh Nguyễn Văn Linh & Bạch Đằng, Hải Châu, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_18_TCH_DANANG",
      "deal_id": "CLM_208_18_TCH_DANANG",
      "brand": "The Coffee House",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_TCH_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "TCH",
      "theme_gradient": "linear-gradient(135deg, #7C2D12, #EA580C)",
      "border_color": "#EA580C",
      "asset_file_or_embed_url": "assets/official-visuals/venue-the-coffee-house-danang.png",
      "source_page_url": "https://thecoffeehouse.com/pages/danh-sach-cua-hang",
      "asset_sha256": findManifestItem('venue-the-coffee-house-danang.png').sha256,
      "brand_and_branch_relation": "The Coffee House - 461 Trần Hưng Đạo & 80 Nguyễn Văn Linh, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_19_PHUCLONG_DN",
      "deal_id": "CLM_208_19_PHUCLONG_DN",
      "brand": "Phúc Long Coffee & Tea",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_PHUCLONG_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "PLG",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #059669)",
      "border_color": "#059669",
      "asset_file_or_embed_url": "assets/official-visuals/venue-phuclong-danang.png",
      "source_page_url": "https://phuclong.com.vn/he-thong-cua-hang-phuc-long",
      "asset_sha256": findManifestItem('venue-phuclong-danang.png').sha256,
      "brand_and_branch_relation": "Phúc Long Coffee & Tea - 61 Nguyễn Văn Linh & TTTM Vincom Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_20_KATINAT_DN",
      "deal_id": "CLM_208_20_KATINAT_DN",
      "brand": "Katinat Saigon Kafe",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_KATINAT_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "KTN",
      "theme_gradient": "linear-gradient(135deg, #1C1917, #78716C)",
      "border_color": "#78716C",
      "asset_file_or_embed_url": "assets/official-visuals/venue-katinat-danang.png",
      "source_page_url": "https://katinat.vn/danh-sach-cua-hang",
      "asset_sha256": findManifestItem('venue-katinat-danang.png').sha256,
      "brand_and_branch_relation": "Katinat Saigon Kafe - 16 Bạch Đằng, P. Thạch Thang, Q. Hải Châu, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_21_COMGA_BABUOI",
      "deal_id": "CLM_208_21_COMGA_BABUOI",
      "brand": "Cơm Gà Bà Buội Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_COMGA_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "CGB",
      "theme_gradient": "linear-gradient(135deg, #713F12, #CA8A04)",
      "border_color": "#CA8A04",
      "asset_file_or_embed_url": "assets/official-visuals/venue-comga-babuoi-danang.png",
      "source_page_url": "https://www.facebook.com/comgababuoi.danang/",
      "asset_sha256": findManifestItem('venue-comga-babuoi-danang.png').sha256,
      "brand_and_branch_relation": "Cơm Gà Bà Buội - 253 Hồ Nghinh, P. Phước Mỹ, Q. Sơn Trà, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_22_BANHTRANG_DAILOC",
      "deal_id": "CLM_208_22_BANHTRANG_DAILOC",
      "brand": "Bánh Tráng Thịt Heo Đại Lộc",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_BANHTRANG_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "BTĐ",
      "theme_gradient": "linear-gradient(135deg, #3F6212, #65A30D)",
      "border_color": "#65A30D",
      "asset_file_or_embed_url": "assets/official-visuals/venue-banhtrang-dailoc-danang.png",
      "source_page_url": "https://maps.google.com/?cid=banhtrangdailocdanang",
      "asset_sha256": findManifestItem('venue-banhtrang-dailoc-danang.png').sha256,
      "brand_and_branch_relation": "Bánh Tráng Đại Lộc - 97 Trưng Nữ Vương, P. Bình Hiên, Q. Hải Châu, Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_23_DANABUS_PUBLIC",
      "deal_id": "CLM_208_23_DANABUS_PUBLIC",
      "brand": "Xe Buýt Danabus Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_DANABUS_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "DNB",
      "theme_gradient": "linear-gradient(135deg, #064E3B, #059669)",
      "border_color": "#059669",
      "asset_file_or_embed_url": "assets/official-visuals/venue-danabus-system-danang.png",
      "source_page_url": "https://danabus.vn/he-thong-tuyen.html",
      "asset_sha256": findManifestItem('venue-danabus-system-danang.png').sha256,
      "brand_and_branch_relation": "Danabus - 497 Bùi Thị Xuân, Sơn Trà & Toàn bộ mạng lưới tuyến nội đô Đà Nẵng",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },
    {
      "card_id": "CARD_215_24_DVC_DANANG",
      "deal_id": "CLM_208_24_DVC_DANANG",
      "brand": "Cổng Dịch Vụ Công Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_EXACT_VENUE_DVC_01",
      "visual_kind": "EXACT_VENUE",
      "monogram": "DVC",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #2563EB)",
      "border_color": "#2563EB",
      "asset_file_or_embed_url": "assets/official-visuals/venue-dvc-danang-portal.png",
      "source_page_url": "https://dichvucong.danang.gov.vn",
      "asset_sha256": findManifestItem('venue-dvc-danang-portal.png').sha256,
      "brand_and_branch_relation": "Trung Tâm Hành Chính & Cổng Dịch Vụ Công TP Đà Nẵng, 24 Trần Phú, Hải Châu",
      "rights_basis": "VERIFIED_PHYSICAL_VENUE_BRANCH_MEDIA_ASSET",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Ảnh địa điểm thực địa cơ sở Đà Nẵng (Đã đối soát)"
    },

    // --- 5 OFFICIAL IDENTITY CANVASES (CHỜ ĐỐI SOÁT HÓA ĐƠN THỰC ĐỊA) ---
    {
      "card_id": "CARD_215_25_MIQUANG_BAMUA",
      "deal_id": "CLM_208_25_MIQUANG_BAMUA",
      "brand": "Mì Quảng Bà Mua",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_MIQUANG_01",
      "visual_kind": "OFFICIAL_IDENTITY",
      "monogram": "MQM",
      "theme_gradient": "linear-gradient(135deg, #713F12, #A16207)",
      "border_color": "#A16207",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://www.facebook.com/miquangbamuadanang/",
      "asset_sha256": null,
      "brand_and_branch_relation": "Mì Quảng Bà Mua - Trần Bình Trọng / Đống Đa, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_215_26_HELIO_NIGHT",
      "deal_id": "CLM_208_26_HELIO_NIGHT",
      "brand": "Chợ Đêm Helio",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_HELIO_01",
      "visual_kind": "OFFICIAL_IDENTITY",
      "monogram": "HLN",
      "theme_gradient": "linear-gradient(135deg, #831843, #BE185D)",
      "border_color": "#BE185D",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://helio.vn/cho-dem-helio.html",
      "asset_sha256": null,
      "brand_and_branch_relation": "Chợ Đêm Helio - Khuôn viên Helio Center, Đường 2/9, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_215_27_SONTRA_NIGHT",
      "deal_id": "CLM_208_27_SONTRA_NIGHT",
      "brand": "Chợ Đêm Sơn Trà",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_SONTRA_01",
      "visual_kind": "OFFICIAL_IDENTITY",
      "monogram": "STN",
      "theme_gradient": "linear-gradient(135deg, #4C1D95, #7C3AED)",
      "border_color": "#7C3AED",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://danangfantasticity.com/cho-dem-son-tra",
      "asset_sha256": null,
      "brand_and_branch_relation": "Chợ Đêm Sơn Trà - Mai Hắc Đế & Lý Nam Đế, An Hải Tây, Sơn Trà, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_215_28_UDN_STUDENT_CENTER",
      "deal_id": "CLM_208_28_UDN_STUDENT_CENTER",
      "brand": "Trung Tâm Hỗ Trợ Sinh Viên ĐH Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_UDN_01",
      "visual_kind": "OFFICIAL_IDENTITY",
      "monogram": "UDN",
      "theme_gradient": "linear-gradient(135deg, #1E3A8A, #3B82F6)",
      "border_color": "#3B82F6",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://udn.vn/ban-cong-tac-hoc-sinh-sinh-vien",
      "asset_sha256": null,
      "brand_and_branch_relation": "Trung Tâm Hỗ Trợ Sinh Viên ĐHĐN - 41 Lê Duẩn, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu — chưa có ảnh ưu đãi/địa điểm xác minh"
    },
    {
      "card_id": "CARD_215_29_PUBLIC_SERVICES",
      "deal_id": "CLM_208_29_PUBLIC_SERVICES",
      "brand": "Thư Viện Tổng Hợp Đà Nẵng",
      "tier": "TIER_PURPLE_VERIFIED_VENUE",
      "visual_asset_id": "ASSET_IDENT_LIBRARY_01",
      "visual_kind": "OFFICIAL_IDENTITY",
      "monogram": "TVT",
      "theme_gradient": "linear-gradient(135deg, #0F766E, #0D9488)",
      "border_color": "#0D9488",
      "asset_file_or_embed_url": null,
      "source_page_url": "https://thuvien.danang.gov.vn",
      "asset_sha256": null,
      "brand_and_branch_relation": "Thư Viện Khoa Học Tổng Hợp Đà Nẵng - 46 Bạch Đằng, Hải Châu, Đà Nẵng",
      "rights_basis": "IDENTITY_CANVAS_NO_MEDIA_LICENSE_ASSERTED",
      "rights_proof_artifact_path": "07_QUALITY_ASSURANCE/runtime_evidence/rights_proof/CARD_VISUAL_RIGHTS_DOSSIER_215.md",
      "captured_at": "2026-08-27T10:54:05.524Z",
      "recheck_timestamp": "2026-09-26T10:54:05.524Z",
      "render_label": "Nhận diện thương hiệu — chưa có ảnh ưu đãi/địa điểm xác minh"
    }
  ]
};

const sotRegistryPath = path.join(repoRoot, '03_SOURCE_OF_TRUTH', 'card_visual_evidence_registry.json');
fs.writeFileSync(sotRegistryPath, JSON.stringify(REGISTRY_215, null, 2), 'utf8');

const qaRegistryPath = path.join(repoRoot, '07_QUALITY_ASSURANCE', 'runtime_evidence', 'card_visual_evidence_registry_215.json');
fs.writeFileSync(qaRegistryPath, JSON.stringify(REGISTRY_215, null, 2), 'utf8');

console.log('✅ Card Visual Evidence Registry 215 successfully written to SOT and QA runtime evidence.');
